# Generated by Django 4.0.1 on 2022-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=4, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('g_can_pause', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
